//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.QoL.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules.QoL.Res.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair Size.
        /// </summary>
        internal static string CrosshairSize_Name {
            get {
                return ResourceManager.GetString("CrosshairSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the Crosshair.
        /// </summary>
        internal static string CrosshairSize_Tooltip {
            get {
                return ResourceManager.GetString("CrosshairSize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable after Search.
        /// </summary>
        internal static string DisableOnSearch_Name {
            get {
                return ResourceManager.GetString("DisableOnSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the module after a wiki search.
        /// </summary>
        internal static string DisableOnSearch_Tooltip {
            get {
                return ResourceManager.GetString("DisableOnSearch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar Expand Direction.
        /// </summary>
        internal static string HotbarExpandDirection_Name {
            get {
                return ResourceManager.GetString("HotbarExpandDirection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction the hotbar should expand towards.
        /// </summary>
        internal static string HotbarExpandDirection_Tooltip {
            get {
                return ResourceManager.GetString("HotbarExpandDirection_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to toggle {0}.
        /// </summary>
        internal static string HotkeyEntry_Description {
            get {
                return ResourceManager.GetString("HotkeyEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hotkey.
        /// </summary>
        internal static string HotkeyEntry_Name {
            get {
                return ResourceManager.GetString("HotkeyEntry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier to link item to chat.
        /// </summary>
        internal static string ModifierToSendToChat_Name {
            get {
                return ResourceManager.GetString("ModifierToSendToChat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Modifier (Default: SHIFT) to link an item to the chat.
        /// </summary>
        internal static string ModifierToSendToChat_Tooltip {
            get {
                return ResourceManager.GetString("ModifierToSendToChat_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type.
        /// </summary>
        internal static string ReturnType_Name {
            get {
                return ResourceManager.GetString("ReturnType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to return after copying the item name..
        /// </summary>
        internal static string ReturnType_Tooltip {
            get {
                return ResourceManager.GetString("ReturnType_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} in the hotbar.
        /// </summary>
        internal static string ShowInHotbar_Description {
            get {
                return ResourceManager.GetString("ShowInHotbar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in hotbar.
        /// </summary>
        internal static string ShowInHotbar_Name {
            get {
                return ResourceManager.GetString("ShowInHotbar_Name", resourceCulture);
            }
        }
    }
}
