//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.QoL.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules.QoL.Res.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow manual zoom.
        /// </summary>
        internal static string AllowManualZoom_Name {
            get {
                return ResourceManager.GetString("AllowManualZoom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using the scroll wheel of your mouse the camera won&apos;t zoom out until the next trigger.
        /// </summary>
        internal static string AllowManualZoom_Tooltip {
            get {
                return ResourceManager.GetString("AllowManualZoom_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair Size.
        /// </summary>
        internal static string CrosshairSize_Name {
            get {
                return ResourceManager.GetString("CrosshairSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the Crosshair.
        /// </summary>
        internal static string CrosshairSize_Tooltip {
            get {
                return ResourceManager.GetString("CrosshairSize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        internal static string DateFormat_Name {
            get {
                return ResourceManager.GetString("DateFormat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format to use for the weekly reset..
        /// </summary>
        internal static string DateFormat_Tooltip {
            get {
                return ResourceManager.GetString("DateFormat_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable after copy.
        /// </summary>
        internal static string DisableOnCopy_Name {
            get {
                return ResourceManager.GetString("DisableOnCopy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the sub module after copying a items name.
        /// </summary>
        internal static string DisableOnCopy_Tooltip {
            get {
                return ResourceManager.GetString("DisableOnCopy_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable on Right Click.
        /// </summary>
        internal static string DisableOnRightClick_Name {
            get {
                return ResourceManager.GetString("DisableOnRightClick_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the sub module when right clicking.
        /// </summary>
        internal static string DisableOnRightClick_Tooltip {
            get {
                return ResourceManager.GetString("DisableOnRightClick_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable after Search.
        /// </summary>
        internal static string DisableOnSearch_Name {
            get {
                return ResourceManager.GetString("DisableOnSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the module after a wiki search.
        /// </summary>
        internal static string DisableOnSearch_Tooltip {
            get {
                return ResourceManager.GetString("DisableOnSearch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar Button Order.
        /// </summary>
        internal static string HotbarButtonSorting_Name {
            get {
                return ResourceManager.GetString("HotbarButtonSorting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of the hotbars buttons.
        /// </summary>
        internal static string HotbarButtonSorting_Tooltip {
            get {
                return ResourceManager.GetString("HotbarButtonSorting_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar Expand Direction.
        /// </summary>
        internal static string HotbarExpandDirection_Name {
            get {
                return ResourceManager.GetString("HotbarExpandDirection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction the hotbar should expand towards.
        /// </summary>
        internal static string HotbarExpandDirection_Tooltip {
            get {
                return ResourceManager.GetString("HotbarExpandDirection_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to toggle {0}.
        /// </summary>
        internal static string HotkeyEntry_Description {
            get {
                return ResourceManager.GetString("HotkeyEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hotkey.
        /// </summary>
        internal static string HotkeyEntry_Name {
            get {
                return ResourceManager.GetString("HotkeyEntry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Layout.
        /// </summary>
        internal static string KeyboardLayout_Name {
            get {
                return ResourceManager.GetString("KeyboardLayout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Layout you use.
        /// </summary>
        internal static string KeyboardLayout_Tooltip {
            get {
                return ResourceManager.GetString("KeyboardLayout_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Max Zoom Out.
        /// </summary>
        internal static string ManualZoom_Name {
            get {
                return ResourceManager.GetString("ManualZoom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual trigger to zoom out the furthest possible..
        /// </summary>
        internal static string ManualZoom_Tooltip {
            get {
                return ResourceManager.GetString("ManualZoom_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier to link item to chat.
        /// </summary>
        internal static string ModifierToSendToChat_Name {
            get {
                return ResourceManager.GetString("ModifierToSendToChat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Modifier (Default: SHIFT) to link an item to the chat.
        /// </summary>
        internal static string ModifierToSendToChat_Tooltip {
            get {
                return ResourceManager.GetString("ModifierToSendToChat_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Clipboard first.
        /// </summary>
        internal static string PasteWaypointFromClipboard_Name {
            get {
                return ResourceManager.GetString("PasteWaypointFromClipboard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if the clipboard content is a waypoint chatlink, if so use that instead of the waypoint code.
        /// </summary>
        internal static string PasteWaypointFromClipboard_Tooltip {
            get {
                return ResourceManager.GetString("PasteWaypointFromClipboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Waypoint.
        /// </summary>
        internal static string PasteWaypointHotkey_Name {
            get {
                return ResourceManager.GetString("PasteWaypointHotkey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to trigger the waypoint paste.
        /// </summary>
        internal static string PasteWaypointHotkey_Tooltip {
            get {
                return ResourceManager.GetString("PasteWaypointHotkey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type.
        /// </summary>
        internal static string ReturnType_Name {
            get {
                return ResourceManager.GetString("ReturnType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to return after copying the item name..
        /// </summary>
        internal static string ReturnType_Tooltip {
            get {
                return ResourceManager.GetString("ReturnType_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Daily Reset.
        /// </summary>
        internal static string ShowDailyReset_Name {
            get {
                return ResourceManager.GetString("ShowDailyReset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the time until daily reset on the bottom left of the minimap.
        /// </summary>
        internal static string ShowDailyReset_Tooltip {
            get {
                return ResourceManager.GetString("ShowDailyReset_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icons.
        /// </summary>
        internal static string ShowIcons_Name {
            get {
                return ResourceManager.GetString("ShowIcons_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icons before the reset countdown.
        /// </summary>
        internal static string ShowIcons_Tooltip {
            get {
                return ResourceManager.GetString("ShowIcons_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} on the hotbar.
        /// </summary>
        internal static string ShowInHotbar_Description {
            get {
                return ResourceManager.GetString("ShowInHotbar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} on hotbar.
        /// </summary>
        internal static string ShowInHotbar_Name {
            get {
                return ResourceManager.GetString("ShowInHotbar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Server Time.
        /// </summary>
        internal static string ShowServerTime_Name {
            get {
                return ResourceManager.GetString("ShowServerTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the server time on the bottom left of the minimap.
        /// </summary>
        internal static string ShowServerTime_Tooltip {
            get {
                return ResourceManager.GetString("ShowServerTime_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltips.
        /// </summary>
        internal static string ShowTooltips_Name {
            get {
                return ResourceManager.GetString("ShowTooltips_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltips when hovering the reset texts.
        /// </summary>
        internal static string ShowTooltips_Tooltip {
            get {
                return ResourceManager.GetString("ShowTooltips_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Weekly Reset.
        /// </summary>
        internal static string ShowWeeklyReset_Name {
            get {
                return ResourceManager.GetString("ShowWeeklyReset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the time until weekly reset on the bottom left of the minimap.
        /// </summary>
        internal static string ShowWeeklyReset_Tooltip {
            get {
                return ResourceManager.GetString("ShowWeeklyReset_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint Chatcode.
        /// </summary>
        internal static string WaypointChatcode_Name {
            get {
                return ResourceManager.GetString("WaypointChatcode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chatcode of the waypoint to post in chat..
        /// </summary>
        internal static string WaypointChatcode_Tooltip {
            get {
                return ResourceManager.GetString("WaypointChatcode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger on camera change.
        /// </summary>
        internal static string ZoomOnCameraChange_Name {
            get {
                return ResourceManager.GetString("ZoomOnCameraChange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger the zoom out on camera changes.
        /// </summary>
        internal static string ZoomOnCameraChange_Tooltip {
            get {
                return ResourceManager.GetString("ZoomOnCameraChange_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger on FoV change.
        /// </summary>
        internal static string ZoomOnFoVChange_Name {
            get {
                return ResourceManager.GetString("ZoomOnFoVChange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger on any Field of View change.
        /// </summary>
        internal static string ZoomOnFoVChange_Tooltip {
            get {
                return ResourceManager.GetString("ZoomOnFoVChange_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string ZoomOutKey_Name {
            get {
                return ResourceManager.GetString("ZoomOutKey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The games &apos;Zoom Out&apos; Keybind in the camera section. This must be set and match else things can go bad..
        /// </summary>
        internal static string ZoomOutKey_Tooltip {
            get {
                return ResourceManager.GetString("ZoomOutKey_Tooltip", resourceCulture);
            }
        }
    }
}
