namespace Kenedia.Modules.BuildsManager.Models
{
    public enum TemplateSlots
    {
        None,
        MainHand,
        OffHand,
        Aquatic,
        AltMainHand,
        AltOffHand,
        AltAquatic,
        Head,
        Shoulder,
        Chest,
        Hand,
        Leg,
        Foot,
        AquaBreather,
        Amulet,
        Accessory_1,
        Accessory_2,
        Ring_1,
        Ring_2,
        Back,
        PvpAmulet,
        Nourishment,
        Enhancement,
        PowerCore,
        PveRelic,
        PvpRelic,

        Profession = 100,
        Race,

        TerrestrialHeal = 200,
        TerrestrialUtility1,
        TerrestrialUtility2,
        TerrestrialUtility3,
        TerrestrialElite,
        AquaticHeal,
        AquaticUtility1,
        AquaticUtility2,
        AquaticUtility3,
        AquaticElite,

        InactiveTerrestrialHeal,
        InactiveTerrestrialUtility1,
        InactiveTerrestrialUtility2,
        InactiveTerrestrialUtility3,
        InactiveTerrestrialElite,
        InactiveAquaticHeal,
        InactiveAquaticUtility1,
        InactiveAquaticUtility2,
        InactiveAquaticUtility3,
        InactiveAquaticElite,

        TerrestrialPet1,
        TerrestrialPet2,
        AquaticPet1,
        AquaticPet2,

        TerrestrialLegend1,
        TerrestrialLegend2,
        AquaticLegend1,
        AquaticLegend2,

        Specialization1,
        Specialization1_MinorTrait,
        Specialization1_MajorTrait,
        Specialization1_GrandmasterTrait,

        Specialization2,
        Specialization2_MinorTrait,
        Specialization2_MajorTrait,
        Specialization2_GrandmasterTrait,

        Specialization3,
        Specialization3_MinorTrait,
        Specialization3_MajorTrait,
        Specialization3_GrandmasterTrait,
    }
}
