//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.BuildsManager.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules.BuildsManager.Res.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory.
        /// </summary>
        internal static string Accessory {
            get {
                return ResourceManager.GetString("Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Legend.
        /// </summary>
        internal static string ActiveLegend {
            get {
                return ResourceManager.GetString("ActiveLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agony Resistance.
        /// </summary>
        internal static string AgonyResistance {
            get {
                return ResourceManager.GetString("AgonyResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet.
        /// </summary>
        internal static string Amulet {
            get {
                return ResourceManager.GetString("Amulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic Pets.
        /// </summary>
        internal static string AquaticPets {
            get {
                return ResourceManager.GetString("AquaticPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armors.
        /// </summary>
        internal static string Armors {
            get {
                return ResourceManager.GetString("Armors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of all armor slots.
        /// </summary>
        internal static string ArmorSlots {
            get {
                return ResourceManager.GetString("ArmorSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Set Filter.
        /// </summary>
        internal static string AutoSetProfession_Name {
            get {
                return ResourceManager.GetString("AutoSetProfession_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set the profession filter to the current profession on profession change.
        /// </summary>
        internal static string AutoSetProfession_Tooltip {
            get {
                return ResourceManager.GetString("AutoSetProfession_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        internal static string BoonDuration {
            get {
                return ResourceManager.GetString("BoonDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Damage.
        /// </summary>
        internal static string ConditionDamage {
            get {
                return ResourceManager.GetString("ConditionDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        internal static string ConditionDuration {
            get {
                return ResourceManager.GetString("ConditionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmTemplateDelete {
            get {
                return ResourceManager.GetString("ConfirmTemplateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL + Left Click to copy the Build Template Code.
        /// </summary>
        internal static string CopyBuildTemplateCode {
            get {
                return ResourceManager.GetString("CopyBuildTemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Template.
        /// </summary>
        internal static string CreateNewTemplate {
            get {
                return ResourceManager.GetString("CreateNewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Template named &apos;{0}&apos;.
        /// </summary>
        internal static string CreateNewTemplateName {
            get {
                return ResourceManager.GetString("CreateNewTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferocity.
        /// </summary>
        internal static string CritDamage {
            get {
                return ResourceManager.GetString("CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not available.
        /// </summary>
        internal static string CurrentlyNotAvailable {
            get {
                return ResourceManager.GetString("CurrentlyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Template.
        /// </summary>
        internal static string DeleteTemplate {
            get {
                return ResourceManager.GetString("DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Skills.
        /// </summary>
        internal static string EliteSkills {
            get {
                return ResourceManager.GetString("EliteSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of all empty armor slots.
        /// </summary>
        internal static string EmptyArmorSlots {
            get {
                return ResourceManager.GetString("EmptyArmorSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of all empty jewellery slots.
        /// </summary>
        internal static string EmptyJewellerySlots {
            get {
                return ResourceManager.GetString("EmptyJewellerySlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of all empty weapon slots.
        /// </summary>
        internal static string EmptyWeaponSlots {
            get {
                return ResourceManager.GetString("EmptyWeaponSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhancement.
        /// </summary>
        internal static string Enhancement {
            get {
                return ResourceManager.GetString("Enhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment.
        /// </summary>
        internal static string Enrichment {
            get {
                return ResourceManager.GetString("Enrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is not the same as the Equipment Template from the game. The games Template can&apos;t be read or shared sadly.
        ///The purpose of this code is to share the modules Equipment Template easily with other module users..
        /// </summary>
        internal static string EquipmentCodeDisclaimer {
            get {
                return ResourceManager.GetString("EquipmentCodeDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill {0}.
        /// </summary>
        internal static string FillEntry {
            get {
                return ResourceManager.GetString("FillEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Power.
        /// </summary>
        internal static string Healing {
            get {
                return ResourceManager.GetString("Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal Skills.
        /// </summary>
        internal static string HealSkills {
            get {
                return ResourceManager.GetString("HealSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Legend.
        /// </summary>
        internal static string InactiveLegend {
            get {
                return ResourceManager.GetString("InactiveLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infusion.
        /// </summary>
        internal static string Infusion {
            get {
                return ResourceManager.GetString("Infusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infusions.
        /// </summary>
        internal static string Infusions {
            get {
                return ResourceManager.GetString("Infusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL + Left Click to copy the item name.
        /// </summary>
        internal static string ItemControlClickToCopyItem {
            get {
                return ResourceManager.GetString("ItemControlClickToCopyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL + Left Click the stat icon to copy the stat name.
        /// </summary>
        internal static string ItemControlClickToCopyStat {
            get {
                return ResourceManager.GetString("ItemControlClickToCopyStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        internal static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewellery.
        /// </summary>
        internal static string Jewellery {
            get {
                return ResourceManager.GetString("Jewellery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of all jewellery slots.
        /// </summary>
        internal static string JewellerySlots {
            get {
                return ResourceManager.GetString("JewellerySlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available through the GW2 API from ArenaNet..
        /// </summary>
        internal static string MissingInfoFromAPI {
            get {
                return ResourceManager.GetString("MissingInfoFromAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Template.
        /// </summary>
        internal static string NewTemplate {
            get {
                return ResourceManager.GetString("NewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nourishment.
        /// </summary>
        internal static string Nourishment {
            get {
                return ResourceManager.GetString("Nourishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        internal static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override {0}.
        /// </summary>
        internal static string OverrideEntry {
            get {
                return ResourceManager.GetString("OverrideEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Id.
        /// </summary>
        internal static string PetId {
            get {
                return ResourceManager.GetString("PetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Core.
        /// </summary>
        internal static string PowerCore {
            get {
                return ResourceManager.GetString("PowerCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        internal static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Sigil.
        /// </summary>
        internal static string PvpSigil {
            get {
                return ResourceManager.GetString("PvpSigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Sigils.
        /// </summary>
        internal static string PvpSigils {
            get {
                return ResourceManager.GetString("PvpSigils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        internal static string Relic {
            get {
                return ResourceManager.GetString("Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all {0}.
        /// </summary>
        internal static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset {0}.
        /// </summary>
        internal static string ResetEntry {
            get {
                return ResourceManager.GetString("ResetEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune.
        /// </summary>
        internal static string Rune {
            get {
                return ResourceManager.GetString("Rune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes.
        /// </summary>
        internal static string Runes {
            get {
                return ResourceManager.GetString("Runes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigil.
        /// </summary>
        internal static string Sigil {
            get {
                return ResourceManager.GetString("Sigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigils.
        /// </summary>
        internal static string Sigils {
            get {
                return ResourceManager.GetString("Sigils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Id.
        /// </summary>
        internal static string SkillId {
            get {
                return ResourceManager.GetString("SkillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        internal static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by profession.
        /// </summary>
        internal static string SortyByProfession {
            get {
                return ResourceManager.GetString("SortyByProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        internal static string Stat {
            get {
                return ResourceManager.GetString("Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a template with the name &apos;{0}&apos;..
        /// </summary>
        internal static string TemplateExistsAlready {
            get {
                return ResourceManager.GetString("TemplateExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrestrial Pets.
        /// </summary>
        internal static string TerrestrialPets {
            get {
                return ResourceManager.GetString("TerrestrialPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toughness.
        /// </summary>
        internal static string Toughness {
            get {
                return ResourceManager.GetString("Toughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait Id.
        /// </summary>
        internal static string TraitId {
            get {
                return ResourceManager.GetString("TraitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Skills.
        /// </summary>
        internal static string UtilitySkills {
            get {
                return ResourceManager.GetString("UtilitySkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of all weapon slots.
        /// </summary>
        internal static string WeaponSlots {
            get {
                return ResourceManager.GetString("WeaponSlots", resourceCulture);
            }
        }
    }
}
