//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Characters.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Characters.Res.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activated.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust {0} settings and tags!.
        /// </summary>
        internal static string AdjustSettings {
            get {
                return ResourceManager.GetString("AdjustSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any {0}.
        /// </summary>
        internal static string AnyProfession {
            get {
                return ResourceManager.GetString("AnyProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armorsmith.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance &amp; Behaviour.
        /// </summary>
        internal static string AppearanceAndBehaviour {
            get {
                return ResourceManager.GetString("AppearanceAndBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armorsmith.
        /// </summary>
        internal static string Armorsmith {
            get {
                return ResourceManager.GetString("Armorsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artificer.
        /// </summary>
        internal static string Artificer {
            get {
                return ResourceManager.GetString("Artificer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Fix.
        /// </summary>
        internal static string AutoFix {
            get {
                return ResourceManager.GetString("AutoFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When failing to swap to a character automatically go through the characters to fix their order..
        /// </summary>
        internal static string AutoFix_Tooltip {
            get {
                return ResourceManager.GetString("AutoFix_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled on the first load of Blish and beeing in character selection the module enters the game. After entering the game it will wait until the MumbleLink and API Token is fully loaded.
        ///Once fully loaded it will switch to the character which is set to be the &quot;Login Character&quot;..
        /// </summary>
        internal static string AutoLogin_Description {
            get {
                return ResourceManager.GetString("AutoLogin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login to selected Character.
        /// </summary>
        internal static string AutoLogin_DisplayName {
            get {
                return ResourceManager.GetString("AutoLogin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best results with Interface set to &apos;Larger&apos;!.
        /// </summary>
        internal static string BestResultLargerDisclaimer {
            get {
                return ResourceManager.GetString("BestResultLargerDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was {0}&apos;s birthday! They are now {1} years old!.
        /// </summary>
        internal static string Birthday_Text {
            get {
                return ResourceManager.GetString("Birthday_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Offset.
        /// </summary>
        internal static string BottomOffset {
            get {
                return ResourceManager.GetString("BottomOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        internal static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture All.
        /// </summary>
        internal static string CaptureAll {
            get {
                return ResourceManager.GetString("CaptureAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Images.
        /// </summary>
        internal static string CaptureImages {
            get {
                return ResourceManager.GetString("CaptureImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved as {0}!.
        /// </summary>
        internal static string CaptureNotification {
            get {
                return ResourceManager.GetString("CaptureNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Potraits.
        /// </summary>
        internal static string CapturePotraits {
            get {
                return ResourceManager.GetString("CapturePotraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Display Option.
        /// </summary>
        internal static string CharacterDisplayOption {
            get {
                return ResourceManager.GetString("CharacterDisplayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Display Size.
        /// </summary>
        internal static string CharacterDisplaySize {
            get {
                return ResourceManager.GetString("CharacterDisplaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        internal static string CharacterName {
            get {
                return ResourceManager.GetString("CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters fixed!.
        /// </summary>
        internal static string CharactersFixed {
            get {
                return ResourceManager.GetString("CharactersFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to swap to {0}.
        /// </summary>
        internal static string CharacterSwap_FailedSwap {
            get {
                return ResourceManager.GetString("CharacterSwap_FailedSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check left ....
        /// </summary>
        internal static string CharacterSwap_Left {
            get {
                return ResourceManager.GetString("CharacterSwap_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to {0}.
        /// </summary>
        internal static string CharacterSwap_LoginTo {
            get {
                return ResourceManager.GetString("CharacterSwap_LoginTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out ....
        /// </summary>
        internal static string CharacterSwap_Logout {
            get {
                return ResourceManager.GetString("CharacterSwap_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to first character ....
        /// </summary>
        internal static string CharacterSwap_MoveFirst {
            get {
                return ResourceManager.GetString("CharacterSwap_MoveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to move to {0}.
        /// </summary>
        internal static string CharacterSwap_MoveTo {
            get {
                return ResourceManager.GetString("CharacterSwap_MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check right ....
        /// </summary>
        internal static string CharacterSwap_Right {
            get {
                return ResourceManager.GetString("CharacterSwap_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching to {0}.
        /// </summary>
        internal static string CharacterSwap_SwitchTo {
            get {
                return ResourceManager.GetString("CharacterSwap_SwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check {0}.
        /// </summary>
        internal static string CheckItem {
            get {
                return ResourceManager.GetString("CheckItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Only Max Crafting.
        /// </summary>
        internal static string CheckOnlyMaxCrafting {
            get {
                return ResourceManager.GetString("CheckOnlyMaxCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef.
        /// </summary>
        internal static string Chef {
            get {
                return ResourceManager.GetString("Chef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        internal static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the module window when logging in to a character..
        /// </summary>
        internal static string CloseWindowOnSwap_Description {
            get {
                return ResourceManager.GetString("CloseWindowOnSwap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window on Character Swap.
        /// </summary>
        internal static string CloseWindowOnSwap_DisplayName {
            get {
                return ResourceManager.GetString("CloseWindowOnSwap_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core {0}.
        /// </summary>
        internal static string CoreProfession {
            get {
                return ResourceManager.GetString("CoreProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any {0} with name {1}.
        /// </summary>
        internal static string CouldNotFindNamedItem {
            get {
                return ResourceManager.GetString("CouldNotFindNamedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafting Profession.
        /// </summary>
        internal static string CraftingProfession {
            get {
                return ResourceManager.GetString("CraftingProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Images.
        /// </summary>
        internal static string CreateImages {
            get {
                return ResourceManager.GetString("CreateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tags.
        /// </summary>
        internal static string CustomTags {
            get {
                return ResourceManager.GetString("CustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deactivated.
        /// </summary>
        internal static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delays.
        /// </summary>
        internal static string Delays {
            get {
                return ResourceManager.GetString("Delays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Tooltip.
        /// </summary>
        internal static string DetailedTooltip {
            get {
                return ResourceManager.GetString("DetailedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a detailed tooltip when hovering a character in the character list. The tooltip will expose all informations available for that character..
        /// </summary>
        internal static string DetailedTooltip_Description {
            get {
                return ResourceManager.GetString("DetailedTooltip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables double clicking the character in the character list to login to that character.
        /// </summary>
        internal static string DoubleClickToEnter_Description {
            get {
                return ResourceManager.GetString("DoubleClickToEnter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click to Swap.
        /// </summary>
        internal static string DoubleClickToEnter_DisplayName {
            get {
                return ResourceManager.GetString("DoubleClickToEnter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubleclick to swap to {0}!.
        /// </summary>
        internal static string DoubleClickToSwap {
            get {
                return ResourceManager.GetString("DoubleClickToSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag this control so the yellow frames contain your character portraits.
        /// </summary>
        internal static string DragOverCharacter_Instructions {
            get {
                return ResourceManager.GetString("DragOverCharacter_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit OCR Region.
        /// </summary>
        internal static string EditOCR {
            get {
                return ResourceManager.GetString("EditOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the OCR Region edit control.
        /// </summary>
        internal static string EditOCR_Tooltip {
            get {
                return ResourceManager.GetString("EditOCR_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Column.
        /// </summary>
        internal static string EmptyColumn {
            get {
                return ResourceManager.GetString("EmptyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Column which does not contain any &apos;white&apos;ish&apos; pixels.
        /// </summary>
        internal static string EmptyColumn_Tooltip {
            get {
                return ResourceManager.GetString("EmptyColumn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Columns.
        /// </summary>
        internal static string EmptyColumns {
            get {
                return ResourceManager.GetString("EmptyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold of how many pixel columns are allowed to contain no content.
        /// </summary>
        internal static string EmptyColumns_Tooltip {
            get {
                return ResourceManager.GetString("EmptyColumns_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns.
        /// </summary>
        internal static string EmptyColumnsThreshold_Tooltip {
            get {
                return ResourceManager.GetString("EmptyColumnsThreshold_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the game automatically after selecting the character in the character selection.
        /// </summary>
        internal static string EnterOnSwap_Description {
            get {
                return ResourceManager.GetString("EnterOnSwap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login after selecting the character.
        /// </summary>
        internal static string EnterOnSwap_DisplayName {
            get {
                return ResourceManager.GetString("EnterOnSwap_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the searchbox is focused pressing &apos;RETURN&apos; will log to the first character in the list..
        /// </summary>
        internal static string EnterToLogin_Description {
            get {
                return ResourceManager.GetString("EnterToLogin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to swap.
        /// </summary>
        internal static string EnterToLogin_DisplayName {
            get {
                return ResourceManager.GetString("EnterToLogin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character swapping is disabled in competition mode!.
        /// </summary>
        internal static string Error_Competivive {
            get {
                return ResourceManager.GetString("Error_Competivive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch characters from the API..
        /// </summary>
        internal static string Error_FailedAPIFetch {
            get {
                return ResourceManager.GetString("Error_FailedAPIFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This API key does not have the required permissions..
        /// </summary>
        internal static string Error_InvalidPermissions {
            get {
                return ResourceManager.GetString("Error_InvalidPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude matches.
        /// </summary>
        internal static string ExcludeMatches {
            get {
                return ResourceManager.GetString("ExcludeMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade the side menus automatically after 2.5 seconds.
        /// </summary>
        internal static string FadeOut_Description {
            get {
                return ResourceManager.GetString("FadeOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade side menu.
        /// </summary>
        internal static string FadeOut_DisplayName {
            get {
                return ResourceManager.GetString("FadeOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all text of the filterbox as one single filter term.
        /// </summary>
        internal static string FilterAsOne_Description {
            get {
                return ResourceManager.GetString("FilterAsOne_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single filter string.
        /// </summary>
        internal static string FilterAsOne_DisplayName {
            get {
                return ResourceManager.GetString("FilterAsOne_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time in milliseconds waited between filtering your characters&apos; panel.
        ///To get the current value you will have to swap module tabs once to update the settings page!.
        /// </summary>
        internal static string FilterDelay_Description {
            get {
                return ResourceManager.GetString("FilterDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Delay ({0} ms).
        /// </summary>
        internal static string FilterDelay_DisplayName {
            get {
                return ResourceManager.GetString("FilterDelay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore any type of diacritics.
        /// </summary>
        internal static string FilterDiacriticsInsensitive_Description {
            get {
                return ResourceManager.GetString("FilterDiacriticsInsensitive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore diacritics.
        /// </summary>
        internal static string FilterDiacriticsInsensitive_DisplayName {
            get {
                return ResourceManager.GetString("FilterDiacriticsInsensitive_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Toggles.
        /// </summary>
        internal static string FilterToggles {
            get {
                return ResourceManager.GetString("FilterToggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch the character name ...{0}{1}.
        /// </summary>
        internal static string FixCharacter_FetchName {
            get {
                return ResourceManager.GetString("FixCharacter_FetchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to next character ....
        /// </summary>
        internal static string FixCharacter_MoveNext {
            get {
                return ResourceManager.GetString("FixCharacter_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name did not change {0}/2 ....
        /// </summary>
        internal static string FixCharacter_NoChange {
            get {
                return ResourceManager.GetString("FixCharacter_NoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing characters ....
        /// </summary>
        internal static string FixCharacter_Start {
            get {
                return ResourceManager.GetString("FixCharacter_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Characters.
        /// </summary>
        internal static string FixCharacters {
            get {
                return ResourceManager.GetString("FixCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a OCR through all your characters to update their current order to match the character selection.
        /// </summary>
        internal static string FixCharacters_Tooltip {
            get {
                return ResourceManager.GetString("FixCharacters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When toggling the main menu to show, automatically focus the search field.
        /// </summary>
        internal static string FocusFilter_Description {
            get {
                return ResourceManager.GetString("FocusFilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus search field.
        /// </summary>
        internal static string FocusFilter_DisplayName {
            get {
                return ResourceManager.GetString("FocusFilter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings &amp; Windows.
        /// </summary>
        internal static string GeneralAndWindows {
            get {
                return ResourceManager.GetString("GeneralAndWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW2 API.
        /// </summary>
        internal static string GW2API {
            get {
                return ResourceManager.GetString("GW2API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huntsman.
        /// </summary>
        internal static string Huntsman {
            get {
                return ResourceManager.GetString("Huntsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Part.
        /// </summary>
        internal static string IgnoredPart {
            get {
                return ResourceManager.GetString("IgnoredPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored part of the image due to the empty column threshold.
        /// </summary>
        internal static string IgnoredPart_Tooltip {
            get {
                return ResourceManager.GetString("IgnoredPart_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include matches.
        /// </summary>
        internal static string IncludeMatches {
            get {
                return ResourceManager.GetString("IncludeMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        internal static string ItemSettings {
            get {
                return ResourceManager.GetString("ItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeweler.
        /// </summary>
        internal static string Jeweler {
            get {
                return ResourceManager.GetString("Jeweler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds.
        /// </summary>
        internal static string Keybinds {
            get {
                return ResourceManager.GetString("Keybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a delay between key presses. This slows down the character swapping and should only be used if your PC is stressed that much so it isn&apos;t able to switch without a delay!.
        /// </summary>
        internal static string KeyDelay_Description {
            get {
                return ResourceManager.GetString("KeyDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Delay {0} ms.
        /// </summary>
        internal static string KeyDelay_DisplayName {
            get {
                return ResourceManager.GetString("KeyDelay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leatherworker.
        /// </summary>
        internal static string Leatherworker {
            get {
                return ResourceManager.GetString("Leatherworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Offset.
        /// </summary>
        internal static string LeftOffset {
            get {
                return ResourceManager.GetString("LeftOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        internal static string LevelAmount {
            get {
                return ResourceManager.GetString("LevelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to get the account name from cached files..
        /// </summary>
        internal static string LoadCachedAccounts_Description {
            get {
                return ResourceManager.GetString("LoadCachedAccounts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from cache.
        /// </summary>
        internal static string LoadCachedAccounts_DisplayName {
            get {
                return ResourceManager.GetString("LoadCachedAccounts_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in character.
        /// </summary>
        internal static string LoginCharacter {
            get {
                return ResourceManager.GetString("LoginCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with &apos;{0}&apos;!.
        /// </summary>
        internal static string LoginWith {
            get {
                return ResourceManager.GetString("LoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to Press to open the logout menu. Must be the same as the game keybind for &apos;Logout&apos;!.
        /// </summary>
        internal static string LogoutDescription {
            get {
                return ResourceManager.GetString("LogoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match all filter.
        /// </summary>
        internal static string MatchAllFilter {
            get {
                return ResourceManager.GetString("MatchAllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match any filter.
        /// </summary>
        internal static string MatchAnyFilter {
            get {
                return ResourceManager.GetString("MatchAnyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool to easily switch characters even with a lot of them!
        ///This will require an API-Key with permissions at least for the &apos;characters&apos; endpoint!.
        /// </summary>
        internal static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Crafting Profession.
        /// </summary>
        internal static string NoCraftingProfession {
            get {
                return ResourceManager.GetString("NoCraftingProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move and Size the yellow frame to contain only the character name row in the character selection!.
        /// </summary>
        internal static string OCR_Instructions {
            get {
                return ResourceManager.GetString("OCR_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset numbers correspond to the region of the box below that is captured for OCR. In order: Left, Top, Right, Bottom. Increasing the numbers makes the capture area smaller. Ideally, you want the values set so that you cannot see any yellow box in the preview above..
        /// </summary>
        internal static string Offset_Tooltip {
            get {
                return ResourceManager.GetString("Offset_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Icons.
        /// </summary>
        internal static string OnlyIcons {
            get {
                return ResourceManager.GetString("OnlyIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only max. Crafting.
        /// </summary>
        internal static string OnlyMaxCrafting {
            get {
                return ResourceManager.GetString("OnlyMaxCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only crafts that are at a 500 rank (Jeweler &amp; Scribe at 400)..
        /// </summary>
        internal static string OnlyMaxCrafting_Description {
            get {
                return ResourceManager.GetString("OnlyMaxCrafting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only maxed out crafting Professions.
        /// </summary>
        internal static string OnlyMaxCrafting_DisplayName {
            get {
                return ResourceManager.GetString("OnlyMaxCrafting_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Text.
        /// </summary>
        internal static string OnlyText {
            get {
                return ResourceManager.GetString("OnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0}.
        /// </summary>
        internal static string OpenItem {
            get {
                return ResourceManager.GetString("OpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Potrait Folder.
        /// </summary>
        internal static string OpenPortraitFolder {
            get {
                return ResourceManager.GetString("OpenPortraitFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the side menu when clicking the search field.
        /// </summary>
        internal static string OpenSidemenuOnSearch_Description {
            get {
                return ResourceManager.GetString("OpenSidemenuOnSearch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open side menu on search.
        /// </summary>
        internal static string OpenSidemenuOnSearch_DisplayName {
            get {
                return ResourceManager.GetString("OpenSidemenuOnSearch_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent the side menus from fading out.
        /// </summary>
        internal static string PinSideMenus_Description {
            get {
                return ResourceManager.GetString("PinSideMenus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin side menus.
        /// </summary>
        internal static string PinSideMenus_DisplayName {
            get {
                return ResourceManager.GetString("PinSideMenus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrait Frame.
        /// </summary>
        internal static string PotraitFrame {
            get {
                return ResourceManager.GetString("PotraitFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrait Gap.
        /// </summary>
        internal static string PotraitGap {
            get {
                return ResourceManager.GetString("PotraitGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrait Size.
        /// </summary>
        internal static string PotraitSize {
            get {
                return ResourceManager.GetString("PotraitSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to a random character in your current list.
        /// </summary>
        internal static string RandomButton_Tooltip {
            get {
                return ResourceManager.GetString("RandomButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh API.
        /// </summary>
        internal static string RefreshAPI {
            get {
                return ResourceManager.GetString("RefreshAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Images.
        /// </summary>
        internal static string RefreshImages {
            get {
                return ResourceManager.GetString("RefreshImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        internal static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Offset.
        /// </summary>
        internal static string RightOffset {
            get {
                return ResourceManager.GetString("RightOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} !.
        /// </summary>
        internal static string RunStateChange {
            get {
                return ResourceManager.GetString("RunStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe.
        /// </summary>
        internal static string Scribe {
            get {
                return ResourceManager.GetString("Scribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c Crafting Profession
        ///-p Profession/Specialization
        ///-r Race
        ///-b Birthday
        ///-m MapName
        ///-t CustomTag
        ///-c Chef; -p Warrior will show all warriors and all chefs.
        /// </summary>
        internal static string SearchGuide {
            get {
                return ResourceManager.GetString("SearchGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a picture.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to Press to toggle the characters menu..
        /// </summary>
        internal static string ShortcutToggle_Description {
            get {
                return ResourceManager.GetString("ShortcutToggle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Menu.
        /// </summary>
        internal static string ShortcutToggle_DisplayName {
            get {
                return ResourceManager.GetString("ShortcutToggle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Characters with Birthday Gifts.
        /// </summary>
        internal static string Show_Birthday_Tooltip {
            get {
                return ResourceManager.GetString("Show_Birthday_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Corner Icon.
        /// </summary>
        internal static string ShowCorner_Name {
            get {
                return ResourceManager.GetString("ShowCorner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show / Hide the Corner Icon of {0}..
        /// </summary>
        internal static string ShowCorner_Tooltip {
            get {
                return ResourceManager.GetString("ShowCorner_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Corner Icon.
        /// </summary>
        internal static string ShowCornerIcon_Description {
            get {
                return ResourceManager.GetString("ShowCornerIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Corner Icon.
        /// </summary>
        internal static string ShowCornerIcon_DisplayName {
            get {
                return ResourceManager.GetString("ShowCornerIcon_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Characters.
        /// </summary>
        internal static string ShowHidden_Tooltip {
            get {
                return ResourceManager.GetString("ShowHidden_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hides {0} in the character list..
        /// </summary>
        internal static string ShowHide_Tooltip {
            get {
                return ResourceManager.GetString("ShowHide_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in List.
        /// </summary>
        internal static string ShowInList {
            get {
                return ResourceManager.GetString("ShowInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0}.
        /// </summary>
        internal static string ShowItem {
            get {
                return ResourceManager.GetString("ShowItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Max Crafting.
        /// </summary>
        internal static string ShowOnlyMaxCrafting {
            get {
                return ResourceManager.GetString("ShowOnlyMaxCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a button next to the search field to switch to a random character of your list.
        /// </summary>
        internal static string ShowRandomButton_Description {
            get {
                return ResourceManager.GetString("ShowRandomButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Random Button.
        /// </summary>
        internal static string ShowRandomButton_Name {
            get {
                return ResourceManager.GetString("ShowRandomButton_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a popup while any automated actions are performed.
        /// </summary>
        internal static string ShowStatusWindow_Description {
            get {
                return ResourceManager.GetString("ShowStatusWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status Popup.
        /// </summary>
        internal static string ShowStatusWindow_Name {
            get {
                return ResourceManager.GetString("ShowStatusWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By {0}.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort {0}.
        /// </summary>
        internal static string SortItem {
            get {
                return ResourceManager.GetString("SortItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Behaviour.
        /// </summary>
        internal static string SwapBehaviour {
            get {
                return ResourceManager.GetString("SwapBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. loading time from ingame to character selection.
        ///To get the current value you will have to swap module tabs once to update the settings page!.
        /// </summary>
        internal static string SwapDelay_Description {
            get {
                return ResourceManager.GetString("SwapDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Delay ({0} ms).
        /// </summary>
        internal static string SwapDelay_DisplayName {
            get {
                return ResourceManager.GetString("SwapDelay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only if the Modifier is pressed trigger character swapping. This will prevent accidientally swapping!.
        /// </summary>
        internal static string SwapModifier_Description {
            get {
                return ResourceManager.GetString("SwapModifier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Modifier to swap.
        /// </summary>
        internal static string SwapModifier_DisplayName {
            get {
                return ResourceManager.GetString("SwapModifier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to {0}.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvE, WvW, Main, ERP ....
        /// </summary>
        internal static string Tag_Placeholder {
            get {
                return ResourceManager.GetString("Tag_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailor.
        /// </summary>
        internal static string Tailor {
            get {
                return ResourceManager.GetString("Tailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and Icons.
        /// </summary>
        internal static string TextAndIcon {
            get {
                return ResourceManager.GetString("TextAndIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle {0}.
        /// </summary>
        internal static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle All.
        /// </summary>
        internal static string ToggleAll {
            get {
                return ResourceManager.GetString("ToggleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle All {0}.
        /// </summary>
        internal static string ToggleAllItem {
            get {
                return ResourceManager.GetString("ToggleAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Potrait Capture.
        /// </summary>
        internal static string TogglePortraitCapture {
            get {
                return ResourceManager.GetString("TogglePortraitCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the Potrait Capture control.
        /// </summary>
        internal static string TogglePortraitCapture_Tooltip {
            get {
                return ResourceManager.GetString("TogglePortraitCapture_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide hidden Characters.
        /// </summary>
        internal static string ToggleVisible {
            get {
                return ResourceManager.GetString("ToggleVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Offset.
        /// </summary>
        internal static string TopOffset {
            get {
                return ResourceManager.GetString("TopOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the game to &apos;WINDOWED&apos; {0} and the UI Scale to &apos;Larger&apos;!.
        /// </summary>
        internal static string UIScale_Error {
            get {
                return ResourceManager.GetString("UIScale_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to set the games Interface Size to &apos;Larger&apos; to get the correct cut outs!.
        /// </summary>
        internal static string UISizeDisclaimer {
            get {
                return ResourceManager.GetString("UISizeDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown.
        /// </summary>
        internal static string Unkown {
            get {
                return ResourceManager.GetString("Unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until Birthday.
        /// </summary>
        internal static string UntilBirthday {
            get {
                return ResourceManager.GetString("UntilBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0}.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a beta feature to determine if you are ingame, watching a cutscene or sit in a loading screen. This feature works well for all common screen ratios. Only struggles in portrait mode..
        /// </summary>
        internal static string UseBetaGameState_Description {
            get {
                return ResourceManager.GetString("UseBetaGameState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Beta Gamestate.
        /// </summary>
        internal static string UseBetaGameState_DisplayName {
            get {
                return ResourceManager.GetString("UseBetaGameState_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use OCR.
        /// </summary>
        internal static string UseOCR {
            get {
                return ResourceManager.GetString("UseOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;Optical Character Recognition&apos; (OCR) to confirm the character name..
        /// </summary>
        internal static string UseOCR_Tooltip {
            get {
                return ResourceManager.GetString("UseOCR_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        internal static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponsmith.
        /// </summary>
        internal static string Weaponsmith {
            get {
                return ResourceManager.GetString("Weaponsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed Mode.
        /// </summary>
        internal static string WindowedMode {
            get {
                return ResourceManager.GetString("WindowedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the game set to Window Mode?.
        /// </summary>
        internal static string WindowedMode_Tooltip {
            get {
                return ResourceManager.GetString("WindowedMode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
