//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.Core.Res {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {

                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules." + Assembly.GetExecutingAssembly().FullName.Split(',')[0].Substring(Assembly.GetExecutingAssembly().FullName.Split(',')[0].LastIndexOf('.') + 1) + ".Res.strings_common", typeof(strings_common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left Corner.
        /// </summary>
        internal static string BottomLeftCorner {
            get {
                return ResourceManager.GetString("BottomLeftCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Offset.
        /// </summary>
        internal static string BottomOffset {
            get {
                return ResourceManager.GetString("BottomOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right Corner.
        /// </summary>
        internal static string BottomRightCorner {
            get {
                return ResourceManager.GetString("BottomRightCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching API data ....
        /// </summary>
        internal static string FetchingApiData {
            get {
                return ResourceManager.GetString("FetchingApiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        internal static string ItemSettings {
            get {
                return ResourceManager.GetString("ItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Offset.
        /// </summary>
        internal static string LeftOffset {
            get {
                return ResourceManager.GetString("LeftOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Offset.
        /// </summary>
        internal static string RightOffset {
            get {
                return ResourceManager.GetString("RightOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RollingChoya {
            get {
                object obj = ResourceManager.GetObject("RollingChoya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Corner Icon for {0}.
        /// </summary>
        internal static string ShowCornerIcon {
            get {
                return ResourceManager.GetString("ShowCornerIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a icon button in the top left of the screen..
        /// </summary>
        internal static string ShowCornerIcon_ttp {
            get {
                return ResourceManager.GetString("ShowCornerIcon_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle {0}.
        /// </summary>
        internal static string ToggleItem {
            get {
                return ResourceManager.GetString("ToggleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left Corner.
        /// </summary>
        internal static string TopLeftCorner {
            get {
                return ResourceManager.GetString("TopLeftCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Offset.
        /// </summary>
        internal static string TopOffset {
            get {
                return ResourceManager.GetString("TopOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right Corner.
        /// </summary>
        internal static string TopRightCorner {
            get {
                return ResourceManager.GetString("TopRightCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These values represent the offset the actual game screen has in relation to the whole client window. Set the values so you don&apos;t see any window frame in the images of the game corners..
        /// </summary>
        internal static string WindowBorder_Tooltip {
            get {
                return ResourceManager.GetString("WindowBorder_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Borders.
        /// </summary>
        internal static string WindowBorders {
            get {
                return ResourceManager.GetString("WindowBorders", resourceCulture);
            }
        }
    }
}
