//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.ReleaseTheChoya.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules.ReleaseTheChoya.Res.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid Combat.
        /// </summary>
        internal static string AvoidCombat {
            get {
                return ResourceManager.GetString("AvoidCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show Choya while in combat.
        /// </summary>
        internal static string AvoidCombat_ttp {
            get {
                return ResourceManager.GetString("AvoidCombat_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Choya Delay ({0}s - {1}s).
        /// </summary>
        internal static string ChoyaDelay {
            get {
                return ResourceManager.GetString("ChoyaDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max delay in seconds between random choya.
        /// </summary>
        internal static string ChoyaDelay_ttp {
            get {
                return ResourceManager.GetString("ChoyaDelay_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Choya Delay ({0}ms - {1}ms).
        /// </summary>
        internal static string ChoyaIdleDelay {
            get {
                return ResourceManager.GetString("ChoyaIdleDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max delay in milliseconds between idle choya.
        /// </summary>
        internal static string ChoyaIdleDelay_ttp {
            get {
                return ResourceManager.GetString("ChoyaIdleDelay_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choya Size ({0}px - {1}px).
        /// </summary>
        internal static string ChoyaSize {
            get {
                return ResourceManager.GetString("ChoyaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max size of the choya.
        /// </summary>
        internal static string ChoyaSize_ttp {
            get {
                return ResourceManager.GetString("ChoyaSize_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choya Speed ({0} - {1}).
        /// </summary>
        internal static string ChoyaSpeed {
            get {
                return ResourceManager.GetString("ChoyaSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max rotation speed of the choya.
        /// </summary>
        internal static string ChoyaSpeed_ttp {
            get {
                return ResourceManager.GetString("ChoyaSpeed_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choya Travel Distance ({0}px - {1}px).
        /// </summary>
        internal static string ChoyaTravelDistance {
            get {
                return ResourceManager.GetString("ChoyaTravelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max speed the choya can roll.
        /// </summary>
        internal static string ChoyaTravelDistance_ttp {
            get {
                return ResourceManager.GetString("ChoyaTravelDistance_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Choya.
        /// </summary>
        internal static string CreateStaticChoya {
            get {
                return ResourceManager.GetString("CreateStaticChoya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a persistent freely placeable choya.
        /// </summary>
        internal static string CreateStaticChoya_ttp {
            get {
                return ResourceManager.GetString("CreateStaticChoya_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delays.
        /// </summary>
        internal static string Delays {
            get {
                return ResourceManager.GetString("Delays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Delay {0}s.
        /// </summary>
        internal static string IdleDelay {
            get {
                return ResourceManager.GetString("IdleDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration in seconds between the last game input and the first spawn of an idle choya.
        /// </summary>
        internal static string IdleDelay_ttp {
            get {
                return ResourceManager.GetString("IdleDelay_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Move Delay {0}s.
        /// </summary>
        internal static string NoMoveDelay {
            get {
                return ResourceManager.GetString("NoMoveDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration in seconds between the last player movement and the first spawn of an idle choya.
        /// </summary>
        internal static string NoMoveDelay_ttp {
            get {
                return ResourceManager.GetString("NoMoveDelay_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Randomly.
        /// </summary>
        internal static string ShowRandomly {
            get {
                return ResourceManager.GetString("ShowRandomly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show choya randomly.
        /// </summary>
        internal static string ShowRandomly_ttp {
            get {
                return ResourceManager.GetString("ShowRandomly_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Idle.
        /// </summary>
        internal static string ShowWhenIdle {
            get {
                return ResourceManager.GetString("ShowWhenIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show idle choya if no game input is detected for {0} seconds.
        /// </summary>
        internal static string ShowWhenIdle_ttp {
            get {
                return ResourceManager.GetString("ShowWhenIdle_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on no Move.
        /// </summary>
        internal static string ShowWhenStandingStill {
            get {
                return ResourceManager.GetString("ShowWhenStandingStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show idle choya if no player movement is detected for {0} seconds.
        /// </summary>
        internal static string ShowWhenStandingStill_ttp {
            get {
                return ResourceManager.GetString("ShowWhenStandingStill_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn Choya.
        /// </summary>
        internal static string SpawnChoyaKey {
            get {
                return ResourceManager.GetString("SpawnChoyaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybind to spawn a choya.
        /// </summary>
        internal static string SpawnChoyaKey_ttp {
            get {
                return ResourceManager.GetString("SpawnChoyaKey_ttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Choya Hunt.
        /// </summary>
        internal static string ToggleChoyaHunt {
            get {
                return ResourceManager.GetString("ToggleChoyaHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the choya hunting minigame.
        /// </summary>
        internal static string ToggleChoyaHunt_ttp {
            get {
                return ResourceManager.GetString("ToggleChoyaHunt_ttp", resourceCulture);
            }
        }
    }
}
